# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: set remote github
        run: git remote set-url origin https://${{ secrets.GITHUBTOKEN }}@github.com/Catastrophe0123/npm-test.git
      - run: git config --global user.email "ci@githubaction.com"
      - run: git config --global user.name "githubaction"
      - name: Print the github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: print the commit message
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}        
        run: echo "$COMMIT_MESSAGE"
      - run: yarn
      - run: yarn build
      - name: Release Tag
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn publish:np patch --no-publish --message="[skip ci] v%s"
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
